# Generated by Django 3.1 on 2020-08-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creatd', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField(null=True)),
                ('short_content', models.CharField(max_length=50)),
                ('number_of_kudos', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=0)),
                ('is_private', models.BooleanField(default=0)),
                ('author', models.ManyToManyField(related_name='authors', to='author.AppUser')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.appuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creatd', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=1000)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
