# Generated by Django 3.1 on 2020-08-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
