# Generated by Django 3.1 on 2020-08-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20200810_2035'),
        ('blog', '0002_auto_20200810_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='author.appuser'),
        ),
    ]
