# Generated by Django 3.1 on 2020-08-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200819_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
