# Generated by Django 3.1 on 2020-08-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='date_creatd',
        ),
        migrations.RemoveField(
            model_name='test',
            name='date_modified',
        ),
    ]
