# Generated by Django 3.1 on 2020-08-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20200825_1354'),
        ('blog', '0010_auto_20200825_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_by',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='author.appuser'),
            preserve_default=False,
        ),
    ]
