# Generated by Django 3.1 on 2020-08-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20200825_1354'),
        ('blog', '0012_auto_20200826_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.appuser'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=10000),
            preserve_default=False,
        ),
    ]
