# Generated by Django 3.1 on 2020-08-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200826_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
