# Generated by Django 3.1 on 2020-08-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20200810_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
