# Generated by Django 3.1 on 2020-08-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20200825_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user',
            new_name='parent_user',
        ),
    ]
